import { Slider, LineEdit } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../../parts/texts.slint";
import { Icons } from "../../styling.slint";
import { ChannelKind } from "../../types.slint";

struct SimpleEffectSingleViewChannelData {
    enabled: bool,
    kind: ChannelKind,
    name: string,
    value: int,
    offset: int,
}

struct SimpleEffectSingleViewItemData {
    channels: [SimpleEffectSingleViewChannelData],
}

global Adopter {
    in property <SimpleEffectSingleViewItemData> item: 
        {
        channels:[
            {
                enabled:true,
                kind: ChannelKind.Dimmer,
                value: 255,
                name: "Dimmer",
                offset:0,
            },
            {
                enabled: true,
                kind: ChannelKind.Red,
                value: 200,
                name: "Red",
                offset:1,
            },
            {
                enabled:false,
                kind: ChannelKind.Green,
                value:0,
                name: "Green",
                offset:2,
            },
            {
                enabled: false,
                kind: ChannelKind.Blue,
                value:0,
                name: "Blue",
                offset:3,
            }
        ]
    };
    in property <string> fixture-query: "#parlight-1";
    in property <string> effect-name: "Scene 1";
    callback update-value(channel-offset: int, value: int);
}

export { Adopter as SimpleEffectSingleViewAdopter }

component Channel inherits Rectangle {
    in property <image> icon;
    in property <length> slider-width;
    in property <bool> enabled;
    in property <ChannelKind> kind;
    in property <int> value;
    in property <string> name;

    callback value-changed(val: int);

    HorizontalLayout {

        Image {
            source: icon;
        }

        PlaneText {
            text: root.name;
            min-width: 20px;
        }

        LineEdit {
            input-type: number;
            width: 30px;
            accepted(text) => {
                value-changed(text.to-float())
            }
        }

        slider := Slider {
            orientation: Orientation.horizontal;
            minimum: 0;
            maximum: 255;
            width: root.slider-width;
            value: root.value;
            changed(value) => value-changed(value);
        }

        PlaneText {
            text: round(slider.value);
        }
    }
}

export component SimpleEffectSingleView {
    property <length> slider-width:200px;
    VerticalLayout {
        alignment: LayoutAlignment.start;
        spacing: 4px;

        MiddleText {
            text: Adopter.effect-name;
        }

        MiddleText {
            text: Adopter.fixture-query;
        }

        VerticalLayout {
            for ch in Adopter.item.channels: Rectangle {
                Channel {
                    icon: Icons.dimmer; //TODO: kindに応じて変える
                    slider-width: 30px; //TODO: hard code
                    enabled: ch.enabled;
                    kind: ch.kind;
                    value: ch.value;
                    name: ch.name;

                    value-changed(val) => {
                        Adopter.update-value(ch.offset, val);
                    }
                }
            }
        }
    }
}
