import { Icons } from "../styling.slint";
import { Palette, ScrollView, LineEdit } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../parts/texts.slint";

export struct FixtureModel { id: string, name: string, modes: [string]}
export struct ManufacturerModel {
    manufacturer: string,
    fixtures: [FixtureModel],
    expanded: bool,
}
component FixtureListItem inherits Rectangle {
    in property <string> fixture-name;
    in property <string> fixture-id;
    in property <bool> selected;
    in-out property <bool> has-focus;
    callback clicked();

    forward-focus: fs;

    changed has-focus => {
        if self.has-focus {
            fs.focus()
        }
        if !self.has-focus {
            fs.clear-focus()
        }
    }

    HorizontalLayout {
        alignment: LayoutAlignment.start;
        spacer := Rectangle {
            width: 2rem;
        }

        PlaneText {
            text: fixture-name;
        }
    }

    states [
        selected when selected: {
            background: Palette.alternate-background;
        }
    ]

    fs := FocusScope {
        changed has-focus => {
            root.has-focus = has-focus;
        }
    }

    TouchArea {
        clicked => root.clicked();
    }

    /*DragArea {
        mime-type: "text/plain";
        data: fixture-id;
    }*/

    ContextMenuArea {
        Menu {
            MenuItem {
                title: @tr("Rename fixture definition");
                activated => {
                    debug("rename requested");
                }
            }

            MenuItem {
                title: @tr("Remove fixture definition");
                activated => {
                    debug("remove requested");
                }
            }
        }
    }
}

export component FixtureListView inherits Rectangle {
    in property <[ManufacturerModel]> manufacturers;
    out property <string> selected-fixture-id;
    property <int> focused-manufacturer;
    callback toggle-expand-manufacturer(name: string);

    accessible-role: list;
    accessible-label: @tr("Fixture List View");
    accessible-id: "fixture-list-view";

    ScrollView {
        vertical-scrollbar-policy: ScrollBarPolicy.always-on;

        layout-manufacturer-list := VerticalLayout {
            alignment: LayoutAlignment.start;
            for m_data[i] in manufacturers: Rectangle {
                accessible-role: button;
                accessible-id: "fixture-list-view-m-" + m_data.manufacturer;
                accessible-label: m_data.manufacturer;
                accessible-expandable: true;
                accessible-expanded: m_data.expanded;
                accessible-action-expand => {
                    toggle-expand-manufacturer(m_data.manufacturer);
                }
                accessible-action-default => {
                    self.accessible-action-expand()
                }

                layout-manufacturer-item := VerticalLayout {
                    header := Rectangle {
                        HorizontalLayout {
                            Image {
                                source: m_data.expanded ? Icons.arrow-drop-down : Icons.arrow-right;
                                width: 22px;
                                height: 22px;
                                vertical-alignment: center;
                            }

                            MiddleText {
                                text: m_data.manufacturer;
                            }
                        }

                        manufacturer-item-ta := TouchArea {
                            width: parent.width;
                            height: parent.height;
                            clicked => {
                                focused-manufacturer = i;
                                toggle-expand-manufacturer(m_data.manufacturer);
                            }
                        }
                    }

                    if m_data.expanded:layout-fixture-list := VerticalLayout {
                        in-out property <int> focused-fixture;

                        alignment: LayoutAlignment.start;

                        for fixture[j] in m_data.fixtures: item := FixtureListItem {
                            accessible-role: button;
                            accessible-id: "fixture-list-view-f-" + m_data.manufacturer + "-" + fixture.name;
                            accessible-label: m_data.manufacturer + "-" + fixture.name;
                            accessible-action-default => {
                                self.clicked()
                            }

                            fixture-name: fixture.name;
                            fixture-id: fixture.id;
                            selected: selected-fixture-id == fixture.id;
                            has-focus: focused-fixture == j;
                            clicked => {
                                selected-fixture-id = fixture.id;
                            }
                        }
                    }

                    manuf-fs := FocusScope { }
                }
            }
        }
    }
}
