import { Icons } from "../styling.slint";
import { Palette, ScrollView, LineEdit } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../parts/texts.slint";

export struct FixtureModel { id: string, name: string, modes: [string]}
export struct ManufacturerModel {
    manufacturer: string,
    fixtures: [FixtureModel],
    expanded: bool,
}
component FixtureListItem inherits Rectangle {
    in property <string> fixture-name;
    in property <string> fixture-id;
    in property <bool> selected;
    callback clicked();

    forward-focus: fs;

    HorizontalLayout {
        alignment: LayoutAlignment.start;
        spacer := Rectangle {
            width: 2rem;
        }

        PlaneText {
            text: fixture-name;
        }
    }

    states [
        selected when selected: {
            background: Palette.alternate-background;
        }
    ]

    fs := FocusScope { }

    TouchArea {
        clicked => root.clicked();
    }

    /*DragArea {
        mime-type: "text/plain";
        data: fixture-id;
    }*/

    ContextMenuArea {
        Menu {
            MenuItem {
                title: @tr("Rename fixture definition");
                activated => {
                    debug("rename requested");
                }
            }

            MenuItem {
                title: @tr("Remove fixture definition");
                activated => {
                    debug("remove requested");
                }
            }
        }
    }
}

export component FixtureListView inherits Rectangle {
    in property <[ManufacturerModel]> manufacturers;
    out property <string> selected-fixture-id;
    callback toggle-expand-manufacturer(name: string);

    accessible-role: list;
    accessible-label: @tr("Fixture List View");
    accessible-id: "fixture-list-view";

    ScrollView {
        vertical-scrollbar-policy: ScrollBarPolicy.always-on;

        layout-manufacturer-list := VerticalLayout {
            alignment: LayoutAlignment.start;
            for manufacturer-model in manufacturers: Rectangle {
                accessible-role: button;
                accessible-id: "fixture-list-view-m-" + manufacturer-model.manufacturer;
                accessible-label: manufacturer-model.manufacturer;
                accessible-expandable: true;
                accessible-expanded: manufacturer-model.expanded;
                accessible-action-expand => {
                    toggle-expand-manufacturer(manufacturer-model.manufacturer)
                }
                accessible-action-default => {
                    self.accessible-action-expand()
                }

                layout-manufacturer-item := VerticalLayout {
                    header := Rectangle {
                        HorizontalLayout {
                            Image {
                                source: manufacturer-model.expanded ? Icons.arrow-drop-down : Icons.arrow-right;
                                width: 22px;
                                height: 22px;
                                vertical-alignment: center;
                            }

                            MiddleText {
                                text: manufacturer-model.manufacturer;
                            }
                        }

                        manufacturer-item-ta := TouchArea {
                            width: parent.width;
                            height: parent.height;
                            clicked => {
                                toggle-expand-manufacturer(manufacturer-model.manufacturer);
                            }
                        }
                    }

                    if manufacturer-model.expanded:layout-fixture-list := VerticalLayout {
                        alignment: LayoutAlignment.start;
                        for fixture in manufacturer-model.fixtures: item := FixtureListItem {
                            accessible-role: button;
                            accessible-id: "fixture-list-view-f-" + manufacturer-model.manufacturer + "-" + fixture.name;
                            accessible-label: manufacturer-model.manufacturer + "-" + fixture.name;
                            accessible-action-default => {
                                self.clicked()
                            }

                            fixture-name: fixture.name;
                            fixture-id: fixture.id;
                            selected: selected-fixture-id == fixture.id;
                            clicked => {
                                selected-fixture-id = fixture.id;
                            }
                        }
                    }

                    FocusScope { }
                }
            }
        }
    }
}
