import { StyleMetrics, Palette, ScrollView } from "std-widgets.slint";
import { BorderHorz, BorderVert } from "../styling.slint";

export struct UniverseViewFixtureData { 
    fixture-id: string, 
    text: string, 
    row: int,
    col: int, 
    length: int,
    is-odd: bool}


global Adopter {
    in property <[UniverseViewFixtureData]> fixtures:[
        // dummy
        { fixture-id:"dummy", text:"MyFixture", row:0, col:0, length:5 }];
    in property <[int]> rows;
    in property <[int]> cols;
}

export {Adopter as UniverseViewAdopter }

export component UniverseView inherits Rectangle {
    property <length> grid-width: root.width/Adopter.cols.length;
    property <length> grid-height: root.height/Adopter.rows.length;

    background: Palette.background;
    
    ScrollView {
        VerticalLayout {
            for i in Adopter.rows: VerticalLayout {
                if i != 0:BorderHorz {
                    height: 1px;
                }
                HorizontalLayout {
                    for j in Adopter.cols: HorizontalLayout {
                        if j != 0 && compute-address()<=512 :BorderVert {
                            width: 1px;
                        }

                        if compute-address()<=512: Rectangle {
                            width: root.grid-width - 1px; //TODO: レスポンシブにしたい
                            height: root.grid-height - 1px;
                            background: Palette.alternate-background;

                            Text {
                                text: compute-address();
                            }
                        }

                        function compute-address()->int {
                            i * Adopter.cols.length+ j + 1
                        }
                    }
                }
            }
        }

        for fxt in Adopter.fixtures: Rectangle {
            x: fxt.col * root.grid-width;
            y: fxt.row * root.grid-height;
            width: fxt.length * root.grid-width;
            height: root.grid-height;
            // TODO: 色のチョイスを変える
            background: fxt.is-odd ? Palette.accent-background : Palette.alternate-background;
            Text {
                text: fxt.text;
                overflow: elide;
                color: Palette.foreground;
            }
        }
    }
}
