import { EffectKind } from "../types.slint";
import { BorderHorz, Icons, Theme } from "../styling.slint";
import {
    SimpleEffectSingleView,
} from "./effects/simple-effect-single-view.slint";
import {
    SequenceEffectSingleView,
} from "./effects/sequence-effect-single-view.slint";
import {
    ParallelEffectSingleView,
} from "./effects/parallel-effect-single-view.slint";
import { MiddleText } from "../parts/texts.slint";
import { GlobalState } from "../global-state.slint";
import { ScrollView } from "std-widgets.slint";

component TabItem inherits Rectangle {
    in property <string> name;
    in property <bool> selected;
    callback clicked();
    HorizontalLayout {
        MiddleText {
            text: name;
        }

        Rectangle {
            background: selected ? gray : black;
            Image {
                source: Icons.close;
            }

            TouchArea {
                clicked => root.clicked();
            }
        }
    }
}

struct EffectEditorPanelData {
    id: string,
    name: string,
}

global Adopter {
    in property <[EffectEditorPanelData]> model:[
        {
            id: "",
            name: "Scene 1",
        },
        {
            id: "",
            name: "Scene 2",
        },
    ];
    in property <string> current-id;
    in property <EffectKind> current-kind;
    callback close(id: string);
}

export { Adopter as EffectEditorPanelAdopter }

export component EffectEditorPanel inherits Rectangle {

    VerticalLayout {
        alignment: LayoutAlignment.start;
        ScrollView {
            HorizontalLayout {
                for data in Adopter.model: TabItem {
                    name: data.name;
                    selected: Adopter.current-id == data.id;
                    clicked => Adopter.close(data.id);
                }
            }
        }

        BorderHorz { }

        if Adopter.current-kind == EffectKind.Simple:SimpleEffectSingleView { }
        if Adopter.current-kind == EffectKind.Sequence:SequenceEffectSingleView { }
        if Adopter.current-kind == EffectKind.Parallel:ParallelEffectSingleView { }
    }
}
