
import { EffectKind } from "../types.slint";
import { LargeText, PlaneText } from "../parts/texts.slint";
import { Icons } from "../styling.slint";



export struct EffectTreeViewItemData {
    id: string,
    kind: EffectKind,
    name: string,
    indent: int,
}

component EffectTreeViewItem inherits Rectangle {
    in property <string> id;
    in property <string> name;
    in property <EffectKind> kind;
    in property <bool> selected;
    callback remove();
    callback clicked();

    pure function get-image(kind: EffectKind) -> image {
        // TODO: それぞれのアイコンを作る
        if kind == EffectKind.Simple {
            return Icons.dimmer;
        }
        if kind == EffectKind.Sequence {
            return Icons.dimmer;
        }
        if kind == EffectKind.Parallel {
            return Icons.dimmer;
        }
        if kind == EffectKind.SimpleTemplate {
            return Icons.dimmer;
        }
        if kind == EffectKind.SequenceTemplate {
            return Icons.dimmer;
        }
        if kind == EffectKind.ParallelTemplate {
            return Icons.dimmer;
        }
        if kind == EffectKind.SimpleSpec {
            return Icons.dimmer;
        }
        if kind == EffectKind.SequenceSpec {
            return Icons.dimmer;
        }
        if kind == EffectKind.ParallelSpec {
            return Icons.dimmer;
        }

        // unreachable
        return Icons.dimmer;
    }

    states [
        selected when root.selected: {
            root.background: gray;
        }
    ]

    VerticalLayout {

        spacer1 := Rectangle {
            height: 2px;
        }

        HorizontalLayout {
            alignment: LayoutAlignment.start;

            margin-left := Rectangle {
                width: 4px;
            }

            Image {
                source: get-image(kind);
            }

            margin := Rectangle {
                width: 4px;
            }

            PlaneText {
                text: name;
            }
        }

        spacer2 := Rectangle {
            height: 2px;
        }
    }

    TouchArea {
        clicked => root.clicked();
    }

    ContextMenuArea {
        Menu {
            MenuItem {
                title: @tr("Remove");
                activated => root.remove();
            }
        }
    }
}

global Adopter {
    in property <[EffectTreeViewItemData]> model:[
        // dummy
        {
            id:"",
            kind: EffectKind.Simple,
            name:"Scene 1",
            indent: 0,
        },
        {
            id: "",
            kind: EffectKind.Sequence,
            name: "Scene 2",
            indent: 0,
        }
    ];
    in property <int> selected-index;

    callback new-simple-effect();
    callback new-simple-effect-spec();
    callback new-sequence-effect();
    callback new-sequence-effect-spec();
    callback new-parallel-effect();
    callback new-parallel-effect-spec();

    callback remove-effect(id: string, kind: EffectKind);
    callback set-selected-effect(id: string, kind: EffectKind);
}

export { Adopter as EffectTreeViewAdopter }

export component EffectTreeView inherits Rectangle {
    VerticalLayout {
        alignment: LayoutAlignment.start;

        LargeText {
            text: @tr("Functions");
        }

        for effect[i] in Adopter.model: EffectTreeViewItem {
            id: effect.id;
            name: effect.name;
            kind: effect.kind;
            selected: i == Adopter.selected-index;

            remove => Adopter.remove-effect(effect.id, effect.kind);
            clicked => Adopter.set-selected-effect(effect.id, effect.kind);
        }

        ContextMenuArea {
            height: 100%;
            Menu {
                MenuItem {
                    title: @tr("New Simple Effect");
                    activated => Adopter.new-simple-effect();
                }

                MenuItem {
                    title: @tr("New Simple Effect Spec");
                    activated => Adopter.new-simple-effect-spec();
                }

                MenuItem {
                    title: @tr("New Sequence Effect");
                    activated => Adopter.new-sequence-effect();
                }

                MenuItem {
                    title: @tr("New Sequence Effect Spec");
                    activated => Adopter.new-sequence-effect-spec();
                }

                MenuItem {
                    title: @tr("New Parallel Effect");
                    activated => Adopter.new-parallel-effect();
                }

                MenuItem {
                    title: @tr("New Parallel Effect Spec");
                    activated => Adopter.new-parallel-effect-spec();
                }
            }
        }
    }
}
