import { Slider, LineEdit } from "std-widgets.slint";
import { PlaneText } from "../parts/texts.slint";
import { Icons } from "../styling.slint";
global Adopter { }

export { Adopter as SimpleFunctionViewAdopter }

component Fader {
    in property <image> icon;
    in property <length> slider-width;
    callback value-changed(val: int);
    HorizontalLayout {
        Image {
            source: icon;
        }

        LineEdit {
            input-type: number;
            width: 30px;
            accepted(text) => {
                value-changed(text.to-float())
            }
        }

        slider := Slider {
            orientation: Orientation.horizontal;
            minimum: 0;
            maximum: 255;
            height: root.slider-width;
            changed(value) => value-changed(value);
        }

        PlaneText {
            text: round(slider.value);
        }
    }
}

export component SimpleFunctionView {
    property <length> slider-width:30px;
    VerticalLayout {
        alignment: LayoutAlignment.start;
        Fader {
            icon: Icons.dimmer;
            slider-width: root.slider-width;
            value-changed(val) => {
            }
        }

        Fader {
            icon: Icons.dimmer;
            slider-width: root.slider-width;
            value-changed(val) => {
            }
        }
    }
}
