import { StyleMetrics, Palette, ScrollView, ComboBox } from "std-widgets.slint";
import { BorderHorz, BorderVert } from "../styling.slint";

export struct UniverseViewFixtureData { fixture-id: string, text: string, row: int, col: int, length: int, is-odd: bool}


global Adopter {
    in property <[UniverseViewFixtureData]> fixtures:[
        // dummy
        { fixture-id:"dummy", text:"MyFixture", row:0, col:0, length:5 }];
    in property <[string]> universes;
    in property <[int]> rows:[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21];
    // dummy
    in property <[int]> cols:[
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23
    ];
    // dummy
    callback universe-changed(selected-index: int);
}

export {Adopter as UniverseViewAdopter }

export component UniverseView inherits Rectangle {
    property <length> grid-width: view.width / Adopter.cols.length;
    property <length> grid-height: view.height / Adopter.rows.length;

    background: Palette.background;

    VerticalLayout {
        ComboBox {
            model: Adopter.universes;
            selected(_current-value) => {
                Adopter.universe-changed(self.current-index)
            }
        }

        view := ScrollView {
            VerticalLayout {
                for i in Adopter.rows: VerticalLayout {
                    if i != 0:BorderHorz {
                        height: 1px;
                    }
                    HorizontalLayout {
                        for j in Adopter.cols: HorizontalLayout {
                            if j != 0 && compute-address() <= 512:BorderVert {
                                width: 1px;
                            }

                            if compute-address() <= 512: Rectangle {
                                width: root.grid-width - 1px; //TODO: レスポンシブにしたい
                            height: root.grid-height - 1px;
                                background: Palette.alternate-background;

                                Text {
                                    text: compute-address();
                                }
                            }

                            function compute-address() -> int {
                                i * Adopter.cols.length + j + 1
                            }
                        }
                    }
                }
            }

            for fxt in Adopter.fixtures: Rectangle {
                x: fxt.col * root.grid-width;
                y: fxt.row * root.grid-height;
                width: fxt.length * root.grid-width;
                height: root.grid-height;
            // TODO: 色のチョイスを変える
            background: fxt.is-odd ? Palette.accent-background : Palette.alternate-background;
                Text {
                    text: fxt.text;
                    overflow: elide;
                    color: Palette.foreground;
                }
            }
        }
    }
}
