import "../assets/fonts/Inter-VariableFont_opsz,wght.ttf";

import { Button, TabWidget, Palette, StandardButton } from "std-widgets.slint";
import { EditorTab, EditorTabs } from "editor-tab.slint";
import { VirtualConsoleTab } from "virtual-console-tab.slint";
import { Preview2D } from "views/preview-2d.slint";
import { FadersView } from "views/faders-view.slint";
import {
    Icons,
    BorderHorz,
    BorderVert,
    Theme,
} from "styling.slint";
import { TimeLineTab } from "timeline-tab.slint";
import { ToolTipArea } from "parts/tooltip.slint";
import { TitleBar } from "titlebar.slint";
import { MiddleText } from "parts/texts.slint";
import { LeftPanel } from "panel-left.slint";
import { Preview3D } from "views/preview-3d.slint";
import { GlobalState } from "global-state.slint";
import { RightPanel } from "panel-right.slint";

export { Preview2DAdopter } from "./views/preview-2d.slint";
export { FadersStore } from "./views/faders-view.slint";
export { FixtureListAdopter } from "./containers/fixture-def-panel.slint";
export { UniverseViewAdopter } from "./views/universe-view.slint";
export { EffectTreeViewAdopter } from "./views/effect-tree-view.slint";
export { SequenceFunctionViewAdopter } from "./views/sequence-function-view.slint";
export { FunctionEditorPanelAdopter } from "./views/function-editor-panel.slint";
export { GlobalState } from "./global-state.slint";

export global MenuBarActions {
    callback save();
    callback save-as();
}

enum TopLevelTabs{
    Editor,
    Timeline,
    VirtualConsole
}

export component AppWindow inherits Window {
    title: "Tsukuyomi";
    icon: Icons.default;
    no-frame: true;
    full-screen: true;
    default-font-family: "Inter";

    property <bool> show-save-dialog;
    // TODO: in propertyにすべき
    in-out property <string> error-message <=> GlobalState.error-message;
    in property <image> texture;
    in property <string> project-path;
    out property <TopLevelTabs> current-tab: index-to-tabs-enum(main-pane.current-index);
    out property <EditorTabs> editor-tab-current-index: editor-tab.current-index;

    // Window events
    callback start_drag();
    callback minimize();
    callback toggle-fullscreen();
    callback close();

    callback key-pressed(ev: KeyEvent) -> EventResult;

    pure function index-to-tabs-enum(index: int) -> TopLevelTabs {
        if index == 0 {
            return TopLevelTabs.Editor;
        }
        if index == 1 {
            return TopLevelTabs.Timeline;
        }
        if index == 2 {
            return TopLevelTabs.VirtualConsole;
        }
        debug("tabs-enum: unknown index");
        return TopLevelTabs.Editor;
    }

    // TODO: Windows, Linux用のフレームレスウィンドウ
    /*if Platform.os == OperatingSystemType.macos:*/MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Open");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Open Recentry");
                activated => {
                };
            }

            MenuSeparator { }

            MenuItem {
                title: @tr("Save");
                activated => {
                    MenuBarActions.save();
                };
            }

            MenuItem {
                title: @tr("Save As");
                activated => {
                };
            }
        }

        Menu {
            title: @tr("Edit");
            MenuItem {
                title: @tr("Undo");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Redo");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Copy");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Paste");
                activated => {
                };
            }
        }

        Menu {
            title: @tr("Help");
            MenuItem {
                title: @tr("About");
                activated => {
                };
            }
        }
    }

    visual-elements := VerticalLayout {
        if Platform.os != OperatingSystemType.macos:title-bar := VerticalLayout {
            TitleBar {
                height: 32px;
                project-path: root.project-path;
                minimize => root.minimize();
                toggle-fullscreen => root.toggle-fullscreen();
                close => root.close();
                show-tooltip(has-hover, x, y, msg) => tooltip.show-tooltip(has-hover, x, y, msg);
                //TODO: バケツリレー
            }

            BorderHorz { }
        }

        content := Rectangle {
            top := Rectangle {
                y: 0;
                height: content.height * 0.7;

                left := LeftPanel {
                    x: 0;
                    width: content.width * 0.25;

                    show-tooltip(has-hover, x, y, msg) => tooltip.show-tooltip(has-hover, x, y, msg);
                }

                BorderVert {
                    x: left.width;
                }

                main-pane := TabWidget {
                    x: left.width;
                    width: content.width * 0.5;

                    Tab {
                        title: @tr("Editor");
                        editor-tab := EditorTab {
                            texture: root.texture;
                            // FIXME: バケツリレー
                        }
                    }

                    Tab {
                        title: @tr("TimeLine");
                        TimeLineTab { }
                    }

                    Tab {
                        title: @tr("Virtual Console");
                        VirtualConsoleTab { }
                    }
                }

                BorderVert {
                    x: left.width + main-pane.width;
                }

                right := RightPanel {
                    x: left.width + main-pane.width;
                    width: content.width * 0.25;
                }
            }

            BorderHorz {
                y: top.height;
            }

            bottom-panel := HorizontalLayout {
                y: top.height;
                height: content.height * 0.3;

                //height: 30%;
                //HorizontalSplit {}

                Rectangle {
                    Text {
                        text: "something?";
                    }
                }

                BorderVert { }

                FadersView { }
            }
        }
    }

    /*TouchArea {
        moved => {
            root.start_drag();
        }
    }*/

    save-dialog := Dialog {
        visible: root.show-save-dialog;
        MiddleText {
            text: @tr("Do you want to save before exit?");
        }

        StandardButton {
            kind: StandardButtonKind.yes;
        }

        StandardButton {
            kind: StandardButtonKind.no;
        }

        StandardButton {
            kind: StandardButtonKind.cancel;
            clicked => {
                save-dialog.visible = false;
            }
        }
    }

    // TODO: 別のウィンドウを出したほうが良さそう
    error-dialog := Dialog {
        visible: root.error-message != "";
        max-width: 0.5 * parent.width;
        max-height: 0.5 * parent.height;
        background: Palette.accent-foreground;

        MiddleText {
            text: root.error-message;
        }

        StandardButton {
            kind: StandardButtonKind.ok;
            clicked => {
                root.error-message = "";
            }
        }
    }

    focus := FocusScope {
        key-pressed(event) => {
            root.key-pressed(event)
        }
    }

    tooltip := ToolTipArea { }
}
