name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2022", "macos-14"]
        command: ["build --release --verbose", "test --verbose"]

    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout main repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
      - name: Install fontconfig on Linux
        if: ${{matrix.os=='ubuntu-latest'}}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libfontconfig1-dev
      - name: Install protoc
        run: |
          set -eux

          PROTOC_VERSION=29.3

          case "${RUNNER_OS}" in
            Linux)
              ARCH=linux-x86_64
              ;;
            macOS)
              ARCH=osx-universal_binary
              ;;
            Windows)
              ARCH=win64
              ;;
            *)
              echo "unsupported OS"
              exit 1
              ;;
          esac

          URL="https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-${ARCH}.zip"

          curl -LO "$URL"

          unzip "protoc-${PROTOC_VERSION}-${ARCH}.zip" -d protoc

      - name: Print protoc version
        run: protoc --version
      - name: Run commands
        run: cargo ${{matrix.command}}
        env:
          PROTOC: "$PWD/protoc/bin"
      - name: Upload a build artifact(windows)
        if: ${{matrix.os=='windows-2022'}}
        uses: actions/upload-artifact@v5
        with:
          name: ${{matrix.os}}
          path: ./target/release/tsukuyomidmx.exe
      - name: Upload a build artifact(ubuntu/macos)
        if: ${{matrix.os!='windows-2022'}}
        uses: actions/upload-artifact@v5
        with:
          name: ${{matrix.os}}
          path: ./target/release/tsukuyomidmx
